"use client";

import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { learningApi, type StudentProfile } from "@/lib/api";

async function hasValidImageSignature(file: File) {
  const bytes = new Uint8Array(await file.slice(0, 12).arrayBuffer());
  const starts = (values: number[]) => values.every((value, index) => bytes[index] === value);
  if (file.type === "image/jpeg") return starts([0xff, 0xd8, 0xff]);
  if (file.type === "image/png") return starts([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  if (file.type === "image/webp") return starts([0x52, 0x49, 0x46, 0x46]) && String.fromCharCode(...bytes.slice(8, 12)) === "WEBP";
  return false;
}

export default function ProfilePage() {
  const router=useRouter(); const [profile,setProfile]=useState<StudentProfile>({name:"",email:""}); const [notice,setNotice]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [avatarPreview,setAvatarPreview]=useState("");
  useEffect(()=>{if(!localStorage.getItem("lumex_token")){router.replace("/login?redirect=/dashboard/profile");return;} learningApi.getProfile().then(setProfile).catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load profile."));},[router]);
  const update=(key:keyof StudentProfile,value:string)=>setProfile(current=>({...current,[key]:value}));
  const uploadAvatar=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setError("");setNotice("");if(!["image/jpeg","image/png","image/webp"].includes(file.type)){setError("Choose a JPEG, PNG, or WebP image.");event.target.value="";return;}if(file.size>5*1024*1024){setError("Profile pictures must be 5 MB or smaller.");event.target.value="";return;}if(!(await hasValidImageSignature(file))){setError("The selected file is not a valid JPEG, PNG, or WebP image.");event.target.value="";return;}setAvatarPreview(URL.createObjectURL(file));setBusy(true);try{const result=await learningApi.uploadAvatar(file);const next={...profile,avatarUrl:result.avatarUrl};setProfile(next);localStorage.setItem("lumex_user",JSON.stringify(next));window.dispatchEvent(new Event("lumex-auth-changed"));setNotice("Profile picture updated.");}catch(reason){setError(reason instanceof Error?reason.message:"Unable to upload profile picture.");}finally{setBusy(false);event.target.value="";}};
  const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setBusy(true);setError("");setNotice("");try{const {name,email,curriculum,course,grade,school,country,mobile,parentName,parentEmail,parentMobile}=profile;const saved=await learningApi.updateProfile({name,email,curriculum,course,grade,school,country,mobile,parentName,parentEmail,parentMobile});setProfile(saved);localStorage.setItem("lumex_user",JSON.stringify(saved));window.dispatchEvent(new Event("lumex-auth-changed"));setNotice("Profile saved.");}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save profile.");}finally{setBusy(false);}};
  const fields:[keyof StudentProfile,string][]=[["name","Student name"],["email","Email address"],["curriculum","Curriculum"],["grade","Grade / level"],["school","School"],["country","Country"],["mobile","Student mobile"],["parentName","Parent / guardian name"],["parentEmail","Parent / guardian email"],["parentMobile","Parent / guardian mobile"]];
  return <main className="min-h-[75vh] bg-[#F4FAFF] py-12"><section className="container-shell max-w-3xl"><h1 className="text-3xl font-extrabold text-[#071B3A]">My profile</h1><p className="mt-2 text-slate-600">Keep your learning and guardian details up to date.</p><form onSubmit={submit} className="mt-7 grid gap-4 rounded-3xl bg-white p-6 shadow-sm sm:grid-cols-2"><div className="flex items-center gap-4 sm:col-span-2"><img src={avatarPreview||profile.avatarUrl||"/logo.png"} alt="Profile" className="h-16 w-16 rounded-full border bg-white object-cover p-1"/><label className="grid gap-1 text-sm font-semibold text-slate-700">Profile picture<input type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadAvatar} disabled={busy} className="block text-sm font-normal"/><span className="text-xs font-normal text-slate-500">JPEG, PNG or WebP · up to 5 MB</span></label></div>{fields.map(([key,label])=><label key={key} className="grid gap-1 text-sm font-semibold text-slate-700">{label}<input type={key==="email"?"email":"text"} value={String(profile[key]||"")} onChange={event=>update(key,event.target.value)} className="rounded-xl border border-slate-200 px-4 py-3 font-normal"/></label>)}{error&&<p role="alert" className="text-sm text-red-600 sm:col-span-2">{error}</p>}{notice&&<p role="status" className="text-sm text-emerald-700 sm:col-span-2">{notice}</p>}<button disabled={busy} className="rounded-xl bg-[#087FF5] px-5 py-3 font-bold text-white disabled:opacity-60 sm:col-span-2">{busy?"Saving…":"Save profile"}</button></form></section></main>;
}
