"use client";
import { Check, ChevronDown, Globe2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";

const languages = [{ code: "en", label: "English", flag: "🇬🇧" }, { code: "ar", label: "العربية", flag: "🇸🇦" }, { code: "hi", label: "हिन्दी", flag: "🇮🇳" }, { code: "ur", label: "اردو", flag: "🇵🇰" }, { code: "fr", label: "Français", flag: "🇫🇷" }, { code: "es", label: "Español", flag: "🇪🇸" }, { code: "zh-CN", label: "中文", flag: "🇨🇳" }, { code: "ms", label: "Bahasa Melayu", flag: "🇲🇾" }, { code: "ta", label: "தமிழ்", flag: "🇮🇳" }];
declare global { interface Window { googleTranslateElementInit?: () => void; google?: { translate?: { TranslateElement: new (options: object, id: string) => unknown } } } }

export function LanguageSelector() {
  const [open, setOpen] = useState(false); const [current, setCurrent] = useState("en"); const ref = useRef<HTMLDivElement>(null);
  useEffect(() => { const saved = localStorage.getItem("lumex_language"); if (saved) setCurrent(saved); if (!document.getElementById("google_translate_element")) { const node = document.createElement("div"); node.id = "google_translate_element"; node.style.display = "none"; document.body.appendChild(node); } if (!document.getElementById("lumex-google-translate")) { window.googleTranslateElementInit = () => { if (window.google?.translate) new window.google.translate.TranslateElement({ pageLanguage: "en", includedLanguages: languages.map((language) => language.code).join(","), autoDisplay: false }, "google_translate_element"); }; const script = document.createElement("script"); script.id = "lumex-google-translate"; script.src = "https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"; script.async = true; document.body.appendChild(script); } const close = (event: MouseEvent) => { if (!ref.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  function select(code: string) { localStorage.setItem("lumex_language", code); setCurrent(code); setOpen(false); document.cookie = `googtrans=/en/${code}; path=/; SameSite=Lax`; if (code === "en") { window.location.reload(); return; } const apply = (attempt = 0) => { const combo = document.querySelector<HTMLSelectElement>(".goog-te-combo"); if (combo) { combo.value = code; combo.dispatchEvent(new Event("change")); } else if (attempt < 20) window.setTimeout(() => apply(attempt + 1), 250); }; apply(); }
  const active = languages.find((language) => language.code === current) ?? languages[0];
  return <div ref={ref} className="relative notranslate" translate="no"><button type="button" onClick={() => setOpen(!open)} className="language-button" aria-expanded={open} aria-haspopup="listbox"><Globe2 size={14}/><span>{active.flag}</span><span className="hidden lg:inline">{active.label}</span><ChevronDown size={13}/></button>{open && <div role="listbox" className="absolute right-0 z-[80] mt-2 max-h-80 w-52 overflow-y-auto rounded-xl border border-slate-200 bg-white p-1 shadow-xl">{languages.map((language) => <button key={language.code} type="button" role="option" aria-selected={current === language.code} onClick={() => select(language.code)} className="flex w-full items-center gap-2 rounded-lg px-3 py-2 text-left text-sm font-medium text-slate-700 hover:bg-slate-50"><span>{language.flag}</span><span className="flex-1">{language.label}</span>{current === language.code && <Check size={15} className="text-[#087FF5]"/>}</button>)}</div>}</div>;
}
