export type Program = {
  slug: string;
  title: string;
  image: string;
  description: string;
  focus: Array<{ level: string; subjects: string }>;
  highlights: Array<{ title: string; description: string }>;
};

// Migrated from the supplied Lurnex course catalogue. Keeping this data in one
// typed source lets cards, detail pages, structured data, and forms stay aligned.
export const programs: Program[] = [
  { slug: "ib", title: "IB Diploma", image: "/assets/images/ibdiploma.png", description: "Personalised support for International Baccalaureate students, from PYP and MYP through the Diploma Programme.", focus: [{ level: "DP 1 & DP 2", subjects: "Mathematics AA/AI, Chemistry, Biology and Physics at HL & SL" }, { level: "MYP 1–5", subjects: "Mathematics, integrated sciences, Physics, Chemistry and Biology" }, { level: "PYP", subjects: "Mathematics and Science" }], highlights: [{ title: "Live 1-to-1 classes", description: "160–200 hours of subject tutoring tailored to the learner." }, { title: "IB exam practice", description: "Past-paper work, revision modules and regular monitored tests." }, { title: "Parent partnership", description: "Fortnightly reports and monthly progress conversations." }] },
  { slug: "igcse", title: "IGCSE Curriculum", image: "/assets/images/igcse.png", description: "Cambridge-aligned tutoring that builds confident subject knowledge and examination technique.", focus: [{ level: "AS & A Level", subjects: "Mathematics (9709)" }, { level: "IGCSE 9 & 10", subjects: "Mathematics, Biology, Chemistry, Physics and coordinated sciences" }, { level: "Lower Secondary 6–8", subjects: "Mathematics and Science" }], highlights: [{ title: "Cambridge question practice", description: "School-exam-focused revision and past-paper coaching." }, { title: "Customised practice", description: "Topic and chapter tests that target gaps." }, { title: "Doubt resolution", description: "Tutor support between lessons when learners need clarity." }] },
  { slug: "ap", title: "Advanced Placement", image: "/assets/images/ap.png", description: "University-level AP preparation for ambitious high-school students.", focus: [{ level: "Math", subjects: "AP Precalculus, Calculus AB/BC and Statistics" }, { level: "Science", subjects: "AP Physics 1 & 2, Chemistry and Biology" }], highlights: [{ title: "FRQ sessions", description: "Real AP-style free-response practice with expert feedback." }, { title: "Rubric-led testing", description: "Unit and full-length tests assessed against AP rubrics." }, { title: "Performance-led content", description: "Learning plans built around individual gaps." }] },
  { slug: "sat", title: "SAT Prep", image: "/assets/images/sat.png", description: "Expert-led SAT preparation combining diagnostics, strategy, daily targeted practice and mock tests.", focus: [{ level: "Math", subjects: "Algebra, advanced math, geometry, trigonometry, statistics and data analysis" }, { level: "Reading & Writing", subjects: "Craft and structure, expression of ideas, information and ideas" }], highlights: [{ title: "Personalised journey", description: "A diagnostic baseline and realistic target-score plan." }, { title: "1-to-1 expert tutoring", description: "Sessions paced to the student’s learning style." }, { title: "Weekly mocks", description: "Progress checks that build confidence for test day." }] },
  { slug: "cbse", title: "CBSE Curriculum", image: "/assets/images/cbse.png", description: "Structured CBSE coaching for strong concepts, board confidence and consistent academic performance.", focus: [{ level: "Grades 11 & 12", subjects: "Physics, Chemistry, Mathematics and Biology" }, { level: "Grades 9 & 10", subjects: "Science and Mathematics" }], highlights: [{ title: "NCERT mastery", description: "In-depth syllabus coverage for board success." }, { title: "Board-pattern practice", description: "Mocks and sample papers aligned to the current marking approach." }, { title: "Practical preparation", description: "Support for practical examinations and viva questions." }] },
  { slug: "neet", title: "NEET Foundations", image: "/assets/images/neet.png", description: "A disciplined, strategic preparation pathway for future medical students.", focus: [{ level: "Biology", subjects: "Botany and Zoology with high-weightage NCERT focus" }, { level: "Physics", subjects: "Conceptual clarity and numerical problem-solving" }, { level: "Chemistry", subjects: "Physical, Organic and Inorganic Chemistry" }], highlights: [{ title: "Rigorous mock tests", description: "Full-syllabus practice under realistic conditions." }, { title: "Performance analysis", description: "Topic and subject insights after every test." }, { title: "High-yield revision", description: "Focused notes and ongoing doubt support." }] },
  { slug: "foundation", title: "Foundation Courses", image: "/assets/images/foundation.png", description: "Early, engaging preparation that strengthens academic fundamentals and competitive-exam readiness.", focus: [{ level: "Grades 8–10", subjects: "Mathematics, Physics, Chemistry, Biology, Logical Reasoning and Analytical Thinking" }], highlights: [{ title: "Olympiad focus", description: "Skills and resources for talent-search examinations." }, { title: "Stress-aware learning", description: "A programme designed to complement school work." }, { title: "Interactive classes", description: "Quizzes, activities and workshops that make concepts stick." }] },
  { slug: "jee", title: "JEE Mains & Advanced", image: "/assets/images/jee.png", description: "Focused engineering entrance preparation with mentoring, advanced practice and test analysis.", focus: [{ level: "JEE Advanced", subjects: "Physics, Chemistry and Mathematics multi-concept problem solving" }, { level: "JEE Mains", subjects: "Full syllabus, speed, accuracy and previous-year trends" }, { level: "Droppers", subjects: "Intensive targeted preparation" }], highlights: [{ title: "Advanced problem solving", description: "Efficient strategies for complex questions." }, { title: "Rigorous test series", description: "Chapter, part-syllabus and full-syllabus assessments." }, { title: "Personal mentorship", description: "Guidance to track progress and sharpen strategy." }] },
];

export const programBySlug = (slug: string) => programs.find((program) => program.slug === slug);
export const courseOptions = ["IB", "Cambridge", "APs (Advanced Placement)", "SAT", "JEE", "NEET", "Foundation", "CBSE", "ICSE/ISC"];
export const gradeOptions: Record<string, string[]> = { IB: ["DP - 2", "DP - 1", "MYP - 5", "MYP - 4", "MYP - 3", "MYP - 2", "MYP - 1", "PYP - 5", "PYP - 4"], Cambridge: ["AS & A Level", "IGCSE 10", "IGCSE 9", "Lower Secondary 8", "Lower Secondary 7", "Lower Secondary 6"], CBSE: ["Grade 12", "Grade 11", "Grade 10", "Grade 9"], Default: ["Grade 12", "Grade 11", "Grade 10", "Grade 9", "Grade 8", "Grade 7", "Grade 6"] };
